(deftheme atom-one-darkest
  "Atom One Darkest - A modified version of the Atom One Dark theme, for Emacs.")

(custom-theme-set-faces
 'atom-one-darkest
 '(success ((t (:foreground "#98C379"))))
 '(warning ((t (:foreground "#E5C07B"))))
 '(error ((t (:foreground "#E06C75" :weight bold))))
 '(link ((t (:weight bold :underline t :foreground "#61AFEF"))))
 '(link-visited ((t (:weight normal :underline t :foreground "#61AFEF"))))
 '(cursor ((t (:background "#F9F9F9"))))
 '(fringe ((t (:inherit (default)))))
 '(region ((t (:background "#3E4451"))))
 '(highlight ((t (:background "#3E4451"))))
 '(hl-line ((t (:background "#2F343D"))))
 '(vertical-border ((t (:foreground "#5C6370"))))
 '(secondary-selection ((t (:background "#121417"))))
 '(query-replace ((t (:inherit isearch))))
 '(minibuffer-prompt ((t (:foreground "#AAAAAA"))))
 '(font-lock-builtin-face ((t (:foreground "#56B6C2"))))
 '(font-lock-comment-face ((t (:foreground "#5C6370"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-face ((t (:inherit font-lock-string-face))))
 '(font-lock-function-name-face ((t (:foreground "#e5c07b"))))
 '(font-lock-keyword-face ((t (:foreground "#c678dd"))))
 '(font-lock-preprocessor-face ((t (:foreground "#e5c07b"))))
 '(font-lock-string-face ((t (:foreground "#98C379"))))
 '(font-lock-type-face ((t (:foreground "#E5C07B"))))
 '(font-lock-constant-face ((t (:foreground "#d19a66"))))
 '(font-lock-variable-name-face ((t (:foreground "#61afef"))))
 '(font-lock-warning-face ((t (:foreground "#5c6370" :weight bold))))
 '(mode-line ((t (:background "#0F1011" :foreground "#AAAAAA"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-inactive ((t (:background "#3E4451"))))
 '(ido-first-match ((t (:foreground "#C678DD" :weight bold))))
 '(ido-only-match ((t (:foreground "#E06C75" :weight bold))))
 '(ido-subdir ((t (:foreground "#61AFEF"))))
 '(ido-virtual ((t (:foreground "#5C6370"))))
 '(ace-jump-face-background ((t (:foreground "#5C6370" :background "#121417" :inverse-video nil))))
 '(ace-jump-face-foreground ((t (:foreground "#E06C75" :background "#121417" :inverse-video nil))))
 '(company-tooltip ((t (:foreground "#ABB2BF" :background "#121417"))))
 '(company-tooltip-annotation ((t (:foreground "#828997" :background "#121417"))))
 '(company-tooltip-selection ((t (:foreground "#ABB2BF" :background "#3E4451"))))
 '(company-tooltip-mouse ((t (:background "#3E4451"))))
 '(company-tooltip-common ((t (:foreground "#E5C07B" :background "#121417"))))
 '(company-tooltip-common-selection ((t (:foreground "#E5C07B" :background "#3E4451"))))
 '(company-preview ((t (:background "#282C34"))))
 '(company-preview-common ((t (:foreground "#E5C07B" :background "#282C34"))))
 '(company-scrollbar-fg ((t (:background "#ABB2BF"))))
 '(company-scrollbar-bg ((t (:background "#121417"))))
 '(compilation-face ((t (:foreground "#ABB2BF"))))
 '(compilation-line-number ((t (:foreground "#828997"))))
 '(compilation-column-number ((t (:foreground "#828997"))))
 '(isearch ((t (:foreground "#282C34" :background "#C678DD"))))
 '(isearch-fail ((t (:foreground "#BE5046" :background nil))))
 '(lazy-highlight ((t (:foreground "#C678DD" :background "#121417" :underline "#C678DD"))))
 '(diff-hl-change ((t (:foreground "#E9C062" :background "#8b733a"))))
 '(diff-hl-delete ((t (:foreground "#CC6666" :background "#7a3d3d"))))
 '(diff-hl-insert ((t (:foreground "#A8FF60" :background "#547f30"))))
 '(dired-directory ((t (:inherit (font-lock-keyword-face)))))
 '(dired-flagged ((t (:inherit (diff-hl-delete)))))
 '(dired-symlink ((t (:foreground "#FD5FF1"))))
 '(helm-header ((t (:foreground "#828997" :background "#282C34" :underline nil :box (:line-width 6 :color "#282C34")))))
 '(helm-source-header ((t (:foreground "#E5C07B" :background "#282C34" :underline nil :weight bold :box (:line-width 6 :color "#282C34")))))
 '(helm-selection ((t (:background "#3E4451"))))
 '(helm-selection-line ((t (:background "#3E4451"))))
 '(helm-visible-mark ((t (:foreground "#282C34" :foreground "#E5C07B"))))
 '(helm-candidate-number ((t (:foreground "#98C379" :background "#121417"))))
 '(helm-separator ((t (:background "#282C34" :foreground "#E06C75"))))
 '(helm-M-x-key ((t (:foreground "#D19A66"))))
 '(helm-bookmark-addressbook ((t (:foreground "#D19A66"))))
 '(helm-bookmark-directory ((t (:foreground nil :background nil :inherit helm-ff-directory))))
 '(helm-bookmark-file ((t (:foreground nil :background nil :inherit helm-ff-file))))
 '(helm-bookmark-gnus ((t (:foreground "#C678DD"))))
 '(helm-bookmark-info ((t (:foreground "#98C379"))))
 '(helm-bookmark-man ((t (:foreground "#E5C07B"))))
 '(helm-bookmark-w3m ((t (:foreground "#C678DD"))))
 '(helm-match ((t (:foreground "#E5C07B"))))
 '(helm-ff-directory ((t (:foreground "#56B6C2" :background "#282C34" :weight bold))))
 '(helm-ff-file ((t (:foreground "#ABB2BF" :background "#282C34" :weight normal))))
 '(helm-ff-executable ((t (:foreground "#98C379" :background "#282C34" :weight normal))))
 '(helm-ff-invalid-symlink ((t (:foreground "#E06C75" :background "#282C34" :weight bold))))
 '(helm-ff-symlink ((t (:foreground "#E5C07B" :background "#282C34" :weight bold))))
 '(helm-ff-prefix ((t (:foreground "#282C34" :background "#E5C07B" :weight normal))))
 '(helm-buffer-not-saved ((t (:foreground "#E06C75"))))
 '(helm-buffer-process ((t (:foreground "#828997"))))
 '(helm-buffer-saved-out ((t (:foreground "#ABB2BF"))))
 '(helm-buffer-size ((t (:foreground "#828997"))))
 '(helm-buffer-directory ((t (:foreground "#C678DD"))))
 '(helm-grep-cmd-line ((t (:foreground "#56B6C2"))))
 '(helm-grep-file ((t (:foreground "#ABB2BF"))))
 '(helm-grep-lineno ((t (:foreground "#828997"))))
 '(helm-grep-finish ((t (:foreground "#E06C75"))))
 '(helm-grep-match ((t (:foreground nil :background nil :inherit helm-match))))
 '(git-commit-comment-action ((t (:foreground "#98C379" :weight bold))))
 '(git-commit-comment-branch-local ((t (:foreground "#61AFEF" :weight bold))))
 '(git-commit-comment-heading ((t (:foreground "#E5C07B" :weight bold))))
 '(magit-section-highlight ((t (:background "#2F343D"))))
 '(magit-section-heading ((t (:foreground "#E5C07B" :weight bold))))
 '(magit-section-heading-selection ((t (:foreground "#ABB2BF" :weight bold))))
 '(magit-diff-file-heading ((t (:weight bold))))
 '(magit-diff-file-heading-highlight ((t (:background "#3E4451" :weight bold))))
 '(magit-diff-file-heading-selection ((t (:foreground "#E5C07B" :background "#2F343D" :weight bold))))
 '(magit-diff-hunk-heading ((t (:foreground "#828997" :background "#3E4451"))))
 '(magit-diff-hunk-heading-highlight ((t (:foreground "#ABB2BF" :background "#5C6370"))))
 '(magit-diff-hunk-heading-selection ((t (:foreground "#C678DD" :background "#5C6370"))))
 '(magit-diff-context ((t (:foreground "#ABB2BF"))))
 '(magit-diff-context-highlight ((t (:background "#121417" :foreground "#ABB2BF"))))
 '(magit-diffstat-added ((t (:foreground "#98C379"))))
 '(magit-diffstat-removed ((t (:foreground "#E06C75"))))
 '(magit-process-ok ((t (:foreground "#98C379"))))
 '(magit-process-ng ((t (:foreground "#E06C75"))))
 '(magit-log-author ((t (:foreground "#E5C07B"))))
 '(magit-log-date ((t (:foreground "#828997"))))
 '(magit-log-graph ((t (:foreground "#AAAAAA"))))
 '(magit-sequence-pick ((t (:foreground "#E5C07B"))))
 '(magit-sequence-stop ((t (:foreground "#98C379"))))
 '(magit-sequence-part ((t (:foreground "#D19A66"))))
 '(magit-sequence-head ((t (:foreground "#61AFEF"))))
 '(magit-sequence-drop ((t (:foreground "#E06C75"))))
 '(magit-sequence-done ((t (:foreground "#828997"))))
 '(magit-sequence-onto ((t (:foreground "#828997"))))
 '(magit-bisect-good ((t (:foreground "#98C379"))))
 '(magit-bisect-skip ((t (:foreground "#D19A66"))))
 '(magit-bisect-bad ((t (:foreground "#E06C75"))))
 '(magit-blame-heading ((t (:background "#121417" :foreground "#828997"))))
 '(magit-blame-hash ((t (:background "#121417" :foreground "#C678DD"))))
 '(magit-blame-name ((t (:background "#121417" :foreground "#E5C07B"))))
 '(magit-blame-date ((t (:background "#121417" :foreground "#5C6370"))))
 '(magit-blame-summary ((t (:background "#121417" :foreground "#828997"))))
 '(magit-dimmed ((t (:foreground "#828997"))))
 '(magit-hash ((t (:foreground "#C678DD"))))
 '(magit-tag ((t (:foreground "#D19A66" :weight bold))))
 '(magit-branch-remote ((t (:foreground "#98C379" :weight bold))))
 '(magit-branch-local ((t (:foreground "#61AFEF" :weight bold))))
 '(magit-branch-current ((t (:foreground "#61AFEF" :weight bold :box t))))
 '(magit-head ((t (:foreground "#61AFEF" :weight bold))))
 '(magit-refname ((t (:background "#282C34" :foreground "#ABB2BF" :weight bold))))
 '(magit-refname-stash ((t (:background "#282C34" :foreground "#ABB2BF" :weight bold))))
 '(magit-refname-wip ((t (:background "#282C34" :foreground "#ABB2BF" :weight bold))))
 '(magit-signature-good ((t (:foreground "#98C379"))))
 '(magit-signature-bad ((t (:foreground "#E06C75"))))
 '(magit-signature-untrusted ((t (:foreground "#D19A66"))))
 '(magit-cherry-unmatched ((t (:foreground "#56B6C2"))))
 '(magit-cherry-equivalent ((t (:foreground "#C678DD"))))
 '(magit-reflog-commit ((t (:foreground "#98C379"))))
 '(magit-reflog-amend ((t (:foreground "#C678DD"))))
 '(magit-reflog-merge ((t (:foreground "#98C379"))))
 '(magit-reflog-checkout ((t (:foreground "#61AFEF"))))
 '(magit-reflog-reset ((t (:foreground "#E06C75"))))
 '(magit-reflog-rebase ((t (:foreground "#C678DD"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#98C379"))))
 '(magit-reflog-remote ((t (:foreground "#56B6C2"))))
 '(magit-reflog-other ((t (:foreground "#56B6C2"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#ABB2BF"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#C678DD"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#61AFEF"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#56B6C2"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#98C379"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#D19A66"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#E5C07B"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#E06C75"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#BE5046"))))
 '(rainbow-delimiters-depth-10-face ((t (:foreground "#ABB2BF"))))
 '(rainbow-delimiters-depth-11-face ((t (:foreground "#828997"))))
 '(rainbow-delimiters-depth-12-face ((t (:foreground "#5C6370"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#0F1011"))))
 '(rbenv-active-ruby-face ((t (:foreground "#98C379"))))
 '(sp-show-pair-mismatch-face ((t (:foreground "#E06C75" :background "#3E4451" :weight bold))))
 '(sp-show-pair-match-face ((t (:background "#3E4451" :weight bold))))
 '(web-mode-symbol-face ((t (:foreground "#D19A66"))))
 '(flx-highlight-face ((t (:inherit (link) :weight bold))))
 '(term-color-black ((t :foreground "#ABB2BF")))
 '(term-color-blue ((t (:foreground "#61AFEF"))))
 '(term-color-cyan ((t :foreground "#56B6C2")))
 '(term-color-green ((t (:foreground "#98C379"))))
 '(term-color-magenta ((t nil)))
 '(term-color-red ((t :foreground "#E06C75")))
 '(term-color-white ((t :foreground "#ABB2BF")))
 '(term-color-yellow ((t (:foreground "#D19A66"))))
 '(org-heading-1 ((t (:background "#332a1b" :height 1.2))))
 '(org-heading-2 ((t (:background "#33181a" :height 1.2))))
 '(org-heading-3 ((t (:background "#27331f" :height 1.2))))
 '(org-heading-4 ((t (:background "#2d1b33" :height 1.2))))
 '(org-heading-5 ((t (:background "#142533" :height 1.2))))
 '(tab-bar ((t (:inherit default))))
 '(tab-bar-tab ((t (:box (:line-width 1 :style nil) :inherit tab-bar))))
 '(tab-bar-tab-inactive ((t (:inherit tab-bar))))
 '(default ((t (:background "#121212" :foreground "#ABB2BF")))))

(provide-theme 'atom-one-darkest)
